version: '3'
volumes:
  node_modules:
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./database:/var/www
    ports:
      - 27017:27017
    command: bash -c "mongod & sleep 2 && mongo admin /var/www/createUsers.js && mongod --shutdown && mongod --auth" 
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/headless-api/
      - node_modules:/var/www/headless-api/node_modules
    command: nodemon src/main.js --exec node_modules/.bin/babel-node
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
